### PR TITLE
Add "label" parameter to morph&hyperspectral analysis fxns

### PR DESCRIPTION
**Pull request by HaleySchuhl**
**Describe your changes**
Add an optional `label` parameter to all functions that store data to the Outputs class so that we can allow for repeated measures and more descriptive data labels. 

**Type of update**
Is this a:
* New feature or feature enhancement
* Work in progress

**Associated issues**
#662 
#660 

**Additional context**

### CODE REVIEW

**Comment by nfahlgren** [comment]
@HaleySchuhl what do you think about simplifying the code a bit so no extra tests would be required for the label parameter?

We could set a default label (maybe `label="default"` ?). Then because label would have a value by default you could remove the:

```python
if label == None:
    prefix = ""
else:
    prefix = label + "_"
```

And just replace it with `prefix = label + "_"`

**Comment by HaleySchuhl** [comment]
> @HaleySchuhl what do you think about simplifying the code a bit so no extra tests would be required for the label parameter?

That's a great idea! I can make that adjustment in both PRs

**Comment by HaleySchuhl** [comment]
I'm currently looking at the `Outputs` doc page, and I came across a question. @nfahlgren is it true that the addition of a `label` parameter for all analysis functions makes the `args.coresult` functionality redundant? Before it let people save the shape of the RGB and NIR data, but now they could just run the function twice (or more) per workflow without clearing and saving new output files.

**Comment by nfahlgren** [comment]
@HaleySchuhl good question. It doesn't currently make it redundant but is something that will help us deprecate the coresult system eventually. The label parameter would allow us to save NIR results as part of the same output file as the VIS results, but coresult also functions in `plantcv-workflow.py` as a mechanism to organize the VIS and NIR inputs to the workflow. Once we have a working solution to #423 we won't need coresult anymore.

**Pull request closed without merging**
