### PR TITLE
Improved handling of empty submasks in analyze.spectral_reflectance

### PR DESCRIPTION
**Pull request by rayn-alex**
**Describe your changes**
Initialized empty analysis output, which is only filled if the (sub)masks are not empty. This avoids errors caused by empty ROIs

**Type of update**
Is this a:
* Bug fix

**Associated issues**
Solves #1450 

**Additional context**
See #1450 

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [x] PR functionality reviewed in a Jupyter Notebook
- [x] All tests pass
- [x] Test coverage remains 100%
- [x] Documentation tested
- [x] New documentation pages added to `plantcv/mkdocs.yml`
- [x] Changes to function input/output signatures added to `updating.md`
- [x] Code reviewed
- [x] PR approved

### CODE REVIEW

**Comment by rayn-alex** [comment]
Ok, well, I'll fix the lines/white spaces issues later

**Comment by rayn-alex** [comment]
@HaleySchuhl from my side, this is done and ready to merge. Please tell me if I missed something.

**Review by HaleySchuhl — APPROVED** [review]
Looks great, thanks for implementing this bugfix @rayn-alex .

**Comment by nfahlgren** [comment]
@all-contributors please add @rayn-alex for code, bug, question

**Pull request merged**
