### PR TITLE
Analyze index march2020 updates

### PR DESCRIPTION
**Pull request by HaleySchuhl**
**Describe your changes**
Minimum and maximum bin parameters now control range of histogram values. There was a plotting mismatch between histogram plotting and calculation since the range for frequency values used to be independent of `min_bin` and `max_bin`. 

**Type of update**
Is this a:
* Bug fix
* Feature enhancement

**Associated issues**
#203 
#526

### CODE REVIEW

**Comment by nfahlgren** [comment]
Wouldn't there still be an issue if the observed min and max for an index image is not the full index range?

**Comment by HaleySchuhl** [comment]
@nfahlgren If the observed min and max are within 0 and the auto-calculated max then there's no problem. In the case where someone sets min=0 and max=1 based on theoretical values there's also no issue even if the observed range is not as wide as the theoretical range. In the case where the observed range is outside of the user defined `min_bin` and `max_bin` then the frequency data will be incomplete but still accurate.

**Comment by nfahlgren** [comment]
Would each of the histograms be on a different scale though? For example, if a given set of NDVI images have a variety of observed max values (0.8, 0.9, 1, etc.). Though I guess the user could set the max.

**Comment by HaleySchuhl** [comment]
@nfahlgren that's correct. Under the default settings there will likely be issues if people want to plot more than one on the same graph. I could update this a little more and have the defaults be `min_bin=0` (which is already the case but this is maybe more descriptive/accurate) and `max_bin=1` since *most* of the indices are expected to range from 0-1 assuming a biologically meaningful context. I could also print a warning statement if the case where observed min or max is outside the user defined range.

**Pull request merged**
