### PR TITLE
OpenCV3 compatibility

### PR DESCRIPTION
**Pull request by fabid**
### Description
Updates in multiple plantcv functions for OpenCV3 compatibility.
The updates are backward compatible with OpenCV2.
Most of the changes relate to the change in the number of returned argument of the cv2.findContours function, other relate to the renaming of opencv functions.

2 changes had to be done in tests.
1 related to an expected number of found objects. I suspect this changed to opencv3 algorithm changes. The test is kept compatible with opencv2
The second one is related to an output image that didn't get named identically after the updates.

### Types of changes

* Internal code updates for openCV3 library compatibility
* Test changes
No functionality should be impacted otherwise

### Checklist:

Tests (and test data) have been updated and passed with OpenCV2 and 3

### CODE REVIEW

**Comment by ic** [comment]
@fabid, tests all pass well here too, as you announced, but the report says coverage has decreased just after the last commit.

I have forked your work and [run it independently on Coveralls, after syncing with danforthcenter/master](https://coveralls.io/builds/13027018). It seems there is no problem of coverage. Perhaps you can just sync with master and update the PR.

**Comment by nfahlgren** [comment]
Apologies for the delay in addressing this PR, OpenCV3 integration is part of our PlantCV3 [roadmap](https://github.com/danforthcenter/plantcv/projects/1) and we needed to finalize the PlantCV2 release before we could start on the PlantCV3 work.

I like that this PR maintains backwards compatibility with OpenCV2 as we would like to support that for at least PlantCV3. Our thinking is that in addition to adding OpenCV3 support that we would do this in conjunction with Python3 support. I have updated the Travis-CI build tests to do a Python3 + OpenCV3 build in conjunction to the preexisting Python2 + OpenCV2 build. I had to tweak some of the tests due to some Python2/3 compatibility issues, but I think this is all working now. There are some remaining errors that at a cursory look appear to be OpenCV3 related: https://travis-ci.org/danforthcenter/plantcv/jobs/320530533.

@fabid if this is something you would like to look at that's great, or if not I can look also and can update this PR as needed, no worries either way. We really appreciate what you have done so far!

**Comment by ic** [comment]
@nfahlgren We use this branch on a small production system (Python 2.7) for a few months. It works fine with OpenCV 3. @fabid and I are not using OpenCV 2 anymore, but the test suites were passing fine.

**Comment by fabid** [comment]
@nfahlgren Thank you for the merge and the work on Python3. Python3 support is definitely great to have!

**Comment by nfahlgren** [comment]
@ic I should clarify. There wasn't anything wrong with the original PR. The only reason the automated checks were marked as failing was because testing coverage dipped very slightly. It's because there were a couple extra lines of code added to check for the OpenCV version. To Travis-CI I added a test suite for Python3 (with OpenCV3) so that these lines are now included in the testing coverage. The other issues I had to fix were all related to Python3, so they weren't directly related to the original PR, just a consequence of me doing the OpenCV3 tests with Python3 instead of 2.

This is a great start to PlantCV3, thanks to you both for contributing! Let us know if there are other things you would find useful that we might be able to put into the v3 roadmap.

**Pull request merged**
