### PR TITLE
Added compatibility for BIP data format of hsi images in read_image

### PR DESCRIPTION
**Pull request by vektorious**
**Changes**
Added the BIP (Bands Interleaved by Pixel) data format for reading hyperspectral images.

**Type of update**
Is this a:
* Feature enhancement
* Related update to documentation

**Associated issues**
Associated Issue: #203 

**Additional context**
Compatibility for BIP data format was missing.

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/stable/pr_review_process/) for instructions on how to review the pull request.
- [x] PR functionality reviewed in a Jupyter Notebook
- [x] All tests pass
- [x] Test coverage remains 100%
- [x] Documentation tested
- [x] New documentation pages added to `plantcv/mkdocs.yml`
- [x] Changes to function input/output signatures added to `updating.md`
- [x] Code reviewed
- [x] PR approved

### CODE REVIEW

**Comment by vektorious** [comment]
Well, the test fails because bip does not rise an error anymore.
I'll fix the test.

**Comment by vektorious** [comment]
Should be good to go @HaleySchuhl 
Seems like I can't trigger the build tests myself.

**Comment by HaleySchuhl** [comment]
Thanks @vektorious for opening this PR! I think @nfahlgren will need to add you as a collaborator for totally automated testing, but I don't think there's any additional tests needed to cover the new code which is always nice. We should be able to get you added to the project soon; thanks again for your contributions!

**Review by HaleySchuhl — APPROVED** [review]
bip -> bup 👍🏼😂

**Comment by vektorious** [comment]
Sure! You are welcome 🙂

**Pull request merged**
