### PR TITLE
Updates to stored "tips" and "branch_pts" getting stored to observations during Morphology workflows 

### PR DESCRIPTION
**Pull request by HaleySchuhl**
**Describe your changes**
Updates with the goal of having a consistent, exact 1:1 ratio between the number of leaves identified, number of leaf "tips", and number of branch points. Logic says that the last (highest) branch point will be shared by the two newest leaves (only talking about maize for this leaf sorting issue right now) but there shouldn't be any cases where the number of branch points is greater than the number of leaves. 

**Type of update**
Is this a:
* New feature or feature enhancement

**Associated issues**
#989 

**Additional context**

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/stable/pr_review_process/) for instructions on how to review the pull request.
- [x] PR functionality reviewed in a Jupyter Notebook
- [x] All tests pass
- [x] Test coverage remains 100%
- [x] Documentation tested
- [x] New documentation pages added to `plantcv/mkdocs.yml`
- [x] Changes to function input/output signatures added to `updating.md`
- [ ] Code reviewed
- [ ] PR approved

### CODE REVIEW

**Comment by HaleySchuhl** [comment]
@Maryan21 have you found this code update to continue to work well with most of the replicates in your dataset? We could continue the discussion here on github or set up another zoom meeting to touch base and chat about any bottlenecks you may have noticed while testing; I know this time of year can get pretty busy 😅

**Comment by Maryan21** [comment]
I used the branch matching function with some new updates to re-order the
leaves properly and we are now testing out the performance manually by
looking through couple hundred images before and after order of the leaves
visually. It would be nice if we can setup a zoom meeting to touch base,
would this Thursday work,  I am available anytime after 12:30pm.

**Comment by HaleySchuhl** [comment]
@Maryan21 Let's plan to chat at 1pm this Thusday.  👍  Can you send a zoom link to my danforth email please?

**Comment by Maryan21** [comment]
Here is the python script I am using for now:  ```
import os, glob


import sys
import json

from plantcv import plantcv as pcv
import cv2
import numpy as np
from plantcv.plantcv import dilate
from plantcv.plantcv import params
from plantcv.plantcv import outputs
from plantcv.plantcv import find_objects
from plantcv.plantcv.morphology import find_branch_pts
from plantcv.plantcv import logical_and
class options:
    def __init__(self):
        # Input image path/filename
        self.image = "."
        # Debug mode = None, "plot", or "print"
        self.debug = "None"
        # Store output images (True/False)
        self.writeimg = False
        # Results path/filename
        self.result = 'results.txt'
        # Image output directory path
        self.outdir = "img"
def multiply_elements(arr, value):
    return [x * value for x in arr]

def ordering_branches(branch_array,leave_length):
    paired_values = list(zip(branch_array, leave_length))
    sorted_paired_values = sorted(enumerate(paired_values), key=lambda x: (-x[1][0][1], -x[1][1]))
    sorted_branch_array = [x[1][0] for x in sorted_paired_values]
    sorted_length = [x[1][1] for x in sorted_paired_values]
    ordered_branch_label = [x[0] for x in sorted_paired_values]
    return sorted_branch_array, ordered_branch_label, sorted_length

def ordering_angles(old_indices,angle_lab,angles):
    ordered_label=[]
    ordered_angle=[]
    for i in range(len(old_indices)):
        ordered_label.append(angle_lab[old_indices[i]])
        ordered_angle.append(angles[old_indices[i]])
    return ordered_label, ordered_angle
def pair_leaf2branch_pts(skel_img, leaf_objects):
    
    # Store debug
    debug = params.debug
    params.debug = None
    
    branch_img = find_branch_pts(skel_img)
    
    # THIS part might need adjustment depending on image resolution?? 
    #trial and error showed that ksize needs to be 5 to ID all 6 example leaves) 
    branch_img = dilate(branch_img, 5, 1) 
    
    branch_objects, _ = find_objects(branch_img, branch_img)
    ordered_branch_pts = [] #empty list with ordered branch points to get stored

    # Make a mask for each leaf segment
    leaf_masks = []
    for i in range(len(leaf_objects)):
        segment_plot = np.zeros(skel_img.shape[:2], np.uint8)
        cv2.drawContours(segment_plot, leaf_objects, i, 255, 1, lineType=8)
        leaf_masks.append(segment_plot)

    # Make a mask for each branch point
    branch_masks = []
    for i in range(len(branch_objects)):
        segment_plot = np.zeros(skel_img.shape[:2], np.uint8)
        cv2.drawContours(segment_plot, branch_objects, i, 255, 1, lineType=8)
        branch_masks.append(segment_plot)

    # Match branch points to leaf segments
    for leaf_id, leaf_mask in enumerate(leaf_masks):
        for branch_id, branch_mask in enumerate(branch_masks):
            overlap_img = logical_and(leaf_mask, branch_mask)
            if np.sum(overlap_img) > 0:
                ordered_branch_pts.append(outputs.observations["default"]["branch_pts"]["value"][branch_id])

    # Reset debug mode
    params.debug = debug
    
    # Overwrite original branch point values
    outputs.observations["default"]["branch_pts"]["value"] = ordered_branch_pts
    outputs.observations["default"]["branch_pts"]["label"] = list(range(0, len(ordered_branch_pts)))
def main():
    # Initialize options
    args = options()
    if len(sys.argv) < 4:
        print("Usage: python filename.py save_folder file")
        sys.exit(1)
    folder = sys.argv[1]
    save = sys.argv[2]
    img_folder=sys.argv[3]
    #folder,save= input("enter foldername directory and savefolder directory: ").split()
    #folder, save="/Users/maryansaid/Desktop/trial/One_plant/ /Users/maryansaid/Desktop/trial/One_Plant_results/

    folderName=str(folder)
    saveFolderName=str(save)
    store=save
    args.image = folderName
    pcv.params.debug = args.debug
    print("Folder name: ", folderName)
    split_path= folderName.split('/')
    plant_name=split_path[5]
    date=split_path[6]
    image=split_path[-1]
    image_name=str(plant_name) + "_"+ str(date)+ "_" +str(image)
    img, path, filename = pcv.readimage(filename=args.image);
    pcv.params.text_size = 1.5
    pcv.params.text_thickness = 5
    pcv.params.line_thickness = 15
    s = pcv.rgb2gray_hsv(rgb_img=img, channel='s')
    s_thresh = pcv.threshold.binary(gray_img=s, threshold=30, max_value=255, object_type='light')
    b = pcv.rgb2gray_lab(rgb_img=img, channel='b')
    b_thresh = pcv.threshold.binary(gray_img=b, threshold=140, max_value=255, object_type='light')
    a = pcv.rgb2gray_lab(rgb_img=img, channel='a')
    a_thresh = pcv.threshold.binary(gray_img=a, threshold=117, max_value=255, object_type='dark')
    bs = pcv.logical_or(bin_img1=s_thresh, bin_img2=b_thresh)
    bsa = pcv.logical_or(bin_img1=bs, bin_img2=a_thresh)
    bsa_fill1 = pcv.fill(bin_img=bsa, size=15)
    bsa_fill3 = pcv.fill(bin_img=bsa_fill1, size=250)
    id_objects, obj_hierarchy = pcv.find_objects(img=img, mask=bsa_fill3)
    roi_custom, roi_hier_custom = pcv.roi.custom(img=img, vertices=[[1070, 1328], [1395, 1328], [1395, 1685], [1890, 1744], [1890, 25], [600, 25], [615, 1744], [1070, 1685]])
    roi_objects, hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=roi_custom, roi_hierarchy=roi_hier_custom, object_contour=id_objects, obj_hierarchy=obj_hierarchy, roi_type='cutto')
    filled_mask1 = pcv.fill(bin_img=kept_mask, size=350)
    filled_mask2 = pcv.closing(gray_img=filled_mask1)
    filled_mask3 = pcv.fill_holes(filled_mask2)
    id_objects, obj_hierarchy = pcv.find_objects(img=img, mask=filled_mask3)
    obj, mask = pcv.object_composition(img=img, contours=id_objects, hierarchy=obj_hierarchy)
    shape_img = pcv.analyze_object(img=img, obj=obj, mask=mask)
    skel = pcv.morphology.skeletonize(mask=mask)
    pruned, segmented_img, segment_objects = pcv.morphology.prune(skel_img=skel, size=100, mask=mask)
    pruned, segmented_img, segment_objects = pcv.morphology.prune(skel_img=pruned, size=50, mask=mask)
    leaf_objects, other_objects = pcv.morphology.segment_sort(skel_img=pruned, objects=segment_objects, mask=mask)
    segmented_img, labeled_id_img = pcv.morphology.segment_id(skel_img=pruned, objects=leaf_objects, mask=mask)
    filled_img = pcv.morphology.fill_segments(mask=mask, objects=leaf_objects)
    labeled_img4 = pcv.morphology.segment_curvature(segmented_img=segmented_img, objects=leaf_objects)
    branch_points_img = pcv.morphology.find_branch_pts(skel_img=pruned, mask=None)
    labeled_img=pcv.morphology.segment_path_length(segmented_img=segmented_img, objects=leaf_objects)
    tips_img = pcv.morphology.find_tips(skel_img=pruned)
    plant_area = pcv.outputs.observations['default']['area']['value']
    plant_height=pcv.outputs.observations['default']['height']['value']
    plant_width=pcv.outputs.observations['default']['width']['value']
    plant_premeter=pcv.outputs.observations['default']['perimeter']['value']
    leave_tips = pcv.outputs.observations['default']['tips']['value']
    branch_points_l=pcv.outputs.observations['default']['branch_pts']['label']
    branch_points_v=pcv.outputs.observations['default']['branch_pts']['value']
    plant_angle=pcv.outputs.observations['default']['segment_curvature']['value']
    angle_labels=pcv.outputs.observations['default']['segment_curvature']['label']
    pair_leaf2branch_pts(pruned, leaf_objects)
    branch_points_l2=pcv.outputs.observations['default']['branch_pts']['label']
    branch_points_v2=pcv.outputs.observations['default']['branch_pts']['value']
    path_lengths = pcv.outputs.observations['default']['segment_path_length']['value']
    if args.writeimg:
        outfile = os.path.join(args.outdir, filename[:-4] + "_shapes.png")
        pcv.print_image(img=shape_img, filename=outfile)
    pcv.params.text_size = 1.5
    pcv.params.text_thickness = 5
    pcv.params.line_thickness = 15
    skel = pcv.morphology.skeletonize(mask=mask)
    if args.writeimg:
        outfile = os.path.join(args.outdir, filename[:-4] + "_leaf_insertion_angles.png")
        pcv.print_image(img=labeled_angle_img, filename=outfile)
    #open result to be stored file
    branch_matching=False
    leaf_num=len(angle_labels)
    branch_num=len(branch_points_l2)
    if leaf_num==branch_num and leaf_num!=0:
        branch_matching=True
    im=image_name
    args.result = save + im + '.json'
    #pixel to cm conversion
    conv=(1.2/38)
    plant_height=plant_height*conv
    plant_area=plant_area*conv
    plant_width=plant_width*conv
    plant_premeter=plant_premeter*conv
    leaf_length=multiply_elements(path_lengths, conv)
    sorted_branch_array,branch_lab,sorted_length= ordering_branches(branch_points_v2,leaf_length)
    angle_label,angle=ordering_angles(branch_lab,angle_labels,plant_angle)
    ordered_leaf_objects = [leaf_objects[i] for i in branch_lab]
    #0

    output_folder = img_folder
    #im_folder = os.path.join(output_folder, im)
    #if not os.path.exists(im_folder):
        #os.makedirs(im_folder)
    output_file_0=im + '.png'
    output_path_0 = os.path.join(output_folder, output_file_0)
    #print(output_path_0)
    cv2.imwrite(output_path_0, img)

    #1
    output_file_1=im + '_unordered' + '.png'
    output_path_1 = os.path.join(output_folder, output_file_1)
    #print(output_path_1)
    cv2.imwrite(output_path_1, labeled_id_img)
    #2. 
    segmented_img, labeled_id_img = pcv.morphology.segment_id(skel_img=pruned, objects=ordered_leaf_objects, mask=mask)
    output_file_2 = im + '__reordere' + '.png'
    output_path_2 = os.path.join(output_folder, output_file_2)
    cv2.imwrite(output_path_2, labeled_id_img)
    data = {}
    if branch_matching==True:
        for i in range(len(plant_angle)):
            data[i] = {
                "image": im,
                "area": plant_area,
                "height": plant_height,
                "width": plant_width,
                "num_of_leaf":leaf_num,
                "Leaf":"Leaf_num_" + str(i),
                "branch_points_label":branch_points_l2[i],
                "branch_points_v_x":branch_points_v2[i][0],
                "branch_points_v_y":branch_points_v2[i][1],
                "sorted_branch_array_x":sorted_branch_array[i][0],
                "sorted_branch_array_y":sorted_branch_array[i][1],
                "leaf_length": leaf_length[i],
                "sorted_leaf_length":sorted_length[i],
                "plant_angle":plant_angle[i],
                "sorted_plant_angle":angle[i]
                }
    json_data = json.dumps(data)
    if branch_matching==True:
        file=open(args.result, 'w')
        file.write(json_data + "\n")
        file.close()

if __name__ == "__main__":
    main() ```

**Comment by HaleySchuhl** [comment]
@Maryan21 I played around with the positive and negative example replicates that you sent me. I adjusted the segmentation steps slightly with downstream skeletonization issues in mind. This mainly involved doing more aggressive dilation to reconnect disjoint pieces of leaf, and it also helps to round out some of the sharp edges that were leading to leaves getting broken up too. 

```
# Install & setup steps here 
# Custom functions 
img, path, filename = pcv.readimage(filename=args.image)
image_name = filename

pcv.params.text_size = 1.5
pcv.params.text_thickness = 5
pcv.params.line_thickness = 15
s = pcv.rgb2gray_hsv(rgb_img=img, channel='s')
s_thresh = pcv.threshold.binary(gray_img=s, threshold=30, max_value=255, object_type='light')

b = pcv.rgb2gray_lab(rgb_img=img, channel='b')
b_thresh = pcv.threshold.binary(gray_img=b, threshold=140, max_value=255, object_type='light')

a = pcv.rgb2gray_lab(rgb_img=img, channel='a')
a_thresh = pcv.threshold.binary(gray_img=a, threshold=117, max_value=255, object_type='dark')

bs = pcv.logical_or(bin_img1=s_thresh, bin_img2=b_thresh)
bsa = pcv.logical_or(bin_img1=bs, bin_img2=a_thresh)

bsa_fill1 = pcv.closing(gray_img=bsa)
bsa_fill3 = pcv.fill(bin_img=bsa_fill1, size=350)

id_objects, obj_hierarchy = pcv.find_objects(img=img, mask=bsa_fill3)

roi_custom, roi_hier_custom = pcv.roi.custom(img=img, vertices=[[1070, 1328], [1395, 1328], [1395, 1685], [1890, 1744], [1890, 25], [600, 25], [615, 1744], [1070, 1685]])
roi_objects, hierarchy, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=roi_custom, roi_hierarchy=roi_hier_custom, object_contour=id_objects, obj_hierarchy=obj_hierarchy, roi_type='cutto')

dilated = pcv.dilate(gray_img=kept_mask, ksize=4, i=2)
filled_mask3 = pcv.fill_holes(dilated)
filled_mask1 = pcv.fill(bin_img=filled_mask3, size=1000)
id_objects, obj_hierarchy = pcv.find_objects(img=img, mask=filled_mask1)
obj, mask = pcv.object_composition(img=img, contours=id_objects, hierarchy=obj_hierarchy)

shape_img = pcv.analyze_object(img=img, obj=obj, mask=mask)

skel = pcv.morphology.skeletonize(mask=mask)
pruned, segmented_img, segment_objects = pcv.morphology.prune(skel_img=skel, size=100, mask=mask)
pruned, segmented_img, segment_objects = pcv.morphology.prune(skel_img=pruned, size=50, mask=mask)

# Haven't changed anything here down 
leaf_objects, other_objects = pcv.morphology.segment_sort(skel_img=pruned, objects=segment_objects, mask=mask)
segmented_img, labeled_id_img = pcv.morphology.segment_id(skel_img=pruned, objects=leaf_objects, mask=mask)
filled_img = pcv.morphology.fill_segments(mask=mask, objects=leaf_objects)
labeled_img4 = pcv.morphology.segment_curvature(segmented_img=segmented_img, objects=leaf_objects)
branch_points_img = pcv.morphology.find_branch_pts(skel_img=pruned, mask=None)
labeled_img=pcv.morphology.segment_path_length(segmented_img=segmented_img, objects=leaf_objects)
tips_img = pcv.morphology.find_tips(skel_img=pruned)
... 
```

**Review by nfahlgren — APPROVED** [review]

**Pull request merged**
