### PR TITLE
Merging plm_homologies workflow into PCV

### PR DESCRIPTION
**Pull request by jgerardhodge**
**Describe your changes**
*The plm_homologies submodule has been created. 
*Migrated acute out of general pool of pcv functions and into plm_homologies submodule.  
*In addition, the de novo homology grouping pipeline consisting of 'space', 'starscape', and 'constella' are being included.  Rudimentary QC scoring can also be performed from this workflow using the 'constellaqc' script provided based on a known standard.

**Type of update**
*New feature or feature enhancement

**Associated issues**
*None

**Additional context**
*None

### CODE REVIEW

**Comment by jgerardhodge** [comment]
After testing acute.py requires debugging as of OpenCV4, findContours function acute is based on has undergone modifications which appears to have changed the output cv2 contour objects generated.   The rest of this submodule is stable, however, acute will periodically fail due to this issue between versions.

**Comment by nfahlgren** [comment]
Hi @jgerardhodge, we're still using OpenCV3 and don't plan to switch to 4 until we release the PlantCV 4.x series.

**Comment by jgerardhodge** [comment]
Good to know, I might explore what's going on in version 4 with this new conda environment I created just to hold onto it as needed for the eventual PCV4 series update.

**Comment by jgerardhodge** [comment]
After doing a few spot checks with this code I think I'm going to do a bit of an overhaul with some of the inputs and outputs in order to create a more synergistic pipeline. I might close this temporarily just so that people don't end up using a deprecated version of these functions until it's finished.

**Pull request closed without merging**
