### PR TITLE
draw_roi bugfix

### PR DESCRIPTION
**Pull request by HaleySchuhl**
draw the ROI bounds regardless of whether the moments can be calculated, and only plot number on debug image when there is more than one ROI

**Describe your changes**
Un-indent the piece of code that is plotting the ROI boundaries, not requirement to be able to calculate moments to be able to draw this. Also adds a check for number of ROIs getting drawn and only adds number when `>1`. 

**Type of update**
Is this a:
* Bug fix and/or feature enhancement

**Associated issues**
- related to #1488 

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [ ] PR functionality reviewed in a Jupyter Notebook
- [ ] All tests pass
- [ ] Test coverage remains 100%
- [ ] Documentation tested
- [ ] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [ ] Code reviewed
- [ ] PR approved

### CODE REVIEW

**Comment by nfahlgren** [comment]
In the previous PR I intentionally changed it to plot the ROI number even if there is only 1 ROI

**Comment by HaleySchuhl** [comment]
> In the previous PR I intentionally changed it to plot the ROI number even if there is only 1 ROI

Ah ok I see @nfahlgren , I found it a little confusing to start plotting a `0` when there is just one, but maybe that's just my personal preference. While using the updated functionality I thought there was a centroid getting drawn at first but depending on resolution & `params.text_size` it's more or less obvious what the oval annotation is. 
image

image

**Comment by nfahlgren** [comment]
In outputs we number the output labels from 1 so I think we should also number the ROIs from 1 instead of 0 now that I look at it

**Comment by HaleySchuhl** [comment]
Yea true, that'll be less confusing all around. Easy enough to implement, I can do that now.

**Review by nfahlgren — APPROVED** [review]

**Pull request merged**
