### PR TITLE
Add "Quick Cutto" ROI function

### PR DESCRIPTION
**Pull request by HaleySchuhl**
**Describe your changes**
A much faster method to making filtered binary and labeled masks from one or more ROIs. Plan to merge this functionality into other plantcv functions in further PRs. 

**Type of update**
Is this a:
*  feature enhancement

**Associated issues**
Reference associated issue numbers. Does this pull request close any issues?

**Additional context**
The iterative nature of `pcv.roi.filter` and therefore also `pcv.create_labels` makes the function speed a bottleneck when image size, mask complexity, and the number of objects/ROIs gets larger.  

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [x] PR functionality reviewed in a Jupyter Notebook
- [x] All tests pass
- [x] Test coverage remains 100%
- [x] Documentation tested
- [ ] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [x] Code reviewed
- [x] PR approved

### CODE REVIEW

**Comment by nfahlgren** [comment]
One quick thing, does that maize image exist already? If so we don't need to include a copy of it in a separate docs folder

**Comment by HaleySchuhl** [comment]
> One quick thing, does that maize image exist already? If so we don't need to include a copy of it in a separate docs folder

I was looking for it but I think it might only exist in the tutorial repo(s). That reminds of something we talked about at dev meeting last week though, about ways to make downloading the repo smaller. Not sure if it would make a significant/any difference relevant to the effort it would require, but there are definitely replicate doc images that we could try to consolidate. Maybe the most glaring example of the duplication I've come across while looking for the maize image is the "original_img" in each of the `pcv.rgb2__` doc pages.

**Comment by nfahlgren** [comment]
Thanks Haley, you're right that the more images there are (docs and tests) the bigger the repo gets and the longer downloads take. Fortunately that only impacts folks installing from source code, the tests and docs are not included in the PyPI and conda packages

**Review by k034b363 — APPROVED** [review]
Looks good to me! I tested it with circle, rectangle, custom, and multi ROI objects and it works just fine with all of them. I removed the docs page, but before it goes back in it'll have to be reviewed again to make sure the output names match the function docstring, but that was all I saw that I would've suggested changing.

**Pull request merged**
