### PR TITLE
Watershed segmentation

### PR DESCRIPTION
**Pull request by JorgeGtz**
**Describe your changes**
Add segment_image_series function. It performs watershed segmentation using the spatial dimensions and time through the frames in the image series.

**Type of update**
Is this a:
* New feature or feature enhancement

**Associated issues**
Associated discussion #668 

**Additional context**
This function aims at solving the problem of segmenting overlapping plants in a multi-plant image series

### CODE REVIEW

**Comment by JorgeGtz** [comment]
Checks were not going

**Comment by nfahlgren** [comment]
I think checks won’t run while there are merge conflicts

**Comment by nfahlgren** [comment]
I think in debug mode all the frames are plotted, I think we need a different way to visualize this as it opens too many figures in Jupyter

**Review by HaleySchuhl — APPROVED** [review]

**Review by HaleySchuhl — APPROVED** [review]

**Comment by nfahlgren** [comment]
Thanks @JorgeGtz and @HaleySchuhl!

**Comment by nfahlgren** [comment]
Thanks @JorgeGtz and @HaleySchuhl!

**Pull request merged**
