### PR TITLE
Add pcv.filters.eccentricity

### PR DESCRIPTION
**Pull request by HaleySchuhl**
**Describe your changes**
Add a new filtering function to the main plantcv workspace that filters objects in a binary mask based on it's eccentricity e.g. keep more circular things while long/oblong objects get filled in. 

**Type of update**
Is this a:
* New feature 

**Associated issues**
* functionality originally added during #754 but splitting apart into more manageable PRs, and updating interactive-object-count from main so we can also merge all those commits eventually. 

**Additional context**
Highly helpful for stomata and pollen grain image cleanup 

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [x] PR functionality reviewed in a Jupyter Notebook
- [x] All tests pass
- [x] Test coverage remains 100%
- [x] Documentation tested
- [x] New documentation pages added to `plantcv/mkdocs.yml`
- [x] Changes to function input/output signatures added to `updating.md`
- [x] Code reviewed
- [x] PR approved

### CODE REVIEW

**Comment by HaleySchuhl** [comment]
Just added materials for the reviewer to the shared google drive, in a folder called [detect_discs_1430](https://drive.google.com/drive/u/0/folders/1jAx0WGJN9sAx2gdFdXLrjp7uyDH0MChC)

**Review by annacasto — APPROVED** [review]
Added a test notebook called pr1430_detect-discs to the shared google drive in the detect_dics folder

**Comment by HaleySchuhl** [comment]
updating function name, starting a `fitler` subpackage and this specific filter will be `pcv.filter.eccentricity`

**Review by HaleySchuhl — COMMENTED** [review]
Looks good to me now! Apologies for not pushing my re-naming commits sooner to save you a minute or two but thanks for the help @nfahlgren for getting this function all fixed up. 

Only minor thing I noticed, but didn't want to rerun test for this, is `updating.md` I think was meant to call the output variable `filtered_mask` instead of `filterec_mask`.

**Pull request merged**
