### PR TITLE
Add VIs to extract index

### PR DESCRIPTION
**Pull request by DannieSheng**
**Describe your changes**
Add new features to extract_index function in hyperspectral subpackage. Include more vegetation indices to be able to calculate. 
List of currently available VIs: "ndvi", "gdvi", "savi", "pri", "aci", "ari", "cai", "cari", "ci_rededge", "cri1", "cri2", "evi", "mari", "mcari", "mtci", "ndre", "psnd_chla", "psnd_chlb", "psnd_car", "psri", "pssr1", "pssr2", "pssr3", "rgri", "rvsi", "sipi", "sr", "vari", "vi_green", "wbi".

**Type of update**
Is this a:
* New feature or feature enhancement
* Work in progress

**Associated issues**
Reference associated issue numbers. Does this pull request close any issues?

**Additional context**

### CODE REVIEW

**Comment by DannieSheng** [comment]
The name should be "Add VIs to extract index"

**Comment by HaleySchuhl** [comment]
I updated the pull request name and pushed a couple commits to get a couple tests to pass. New indicies require wavelengths beyond the range of images we're taking at the danforth center, perhaps we can borrow some data for testing those that need >1000 nm bands?

**Comment by nfahlgren** [comment]
We could get Headwall SWIR (~1000-2500 or something like that) data from TERRA-REF. We would need to subset it to have a small test dataset.

**Comment by maliagehan** [comment]
I think splitting out the indicies that require SWIR for now might be a good idea, but I like the idea of using some of the Terra-ref data for testing longer term.

**Comment by nfahlgren** [comment]
Now that the other PR is merged, can this PR be closed? Is the branch still needed?

**Comment by DannieSheng** [comment]
> Now that the other PR is merged, can this PR be closed? Is the branch still needed?

I don't think it still needed

**Comment by nfahlgren** [comment]
Thanks @DannieSheng!

**Pull request closed without merging**
